### ISSUE TITLE
Wally version does not work

### ISSUE THREAD

**Issue by Tazmondo** [smartbone-org/SmartBone-2#33]
It appears that the `default.project.json` refers to `src-build` while only `src` gets uploaded to wally.

So when you install from wally, Rojo gets confused because it cannot find `src-build`

Looks like replacing `src` with `src-build` in the `wally.toml` should fix it

**Comment by JakeyWasTaken** [comment]
Fixed in [v0.4.1](https://github.com/smartbone-org/SmartBone-2/releases/tag/v0.4.1)

**Comment by JakeyWasTaken** [comment]
Correction, v0.4.2. Didnt merge PR for 0.4.1
