### ISSUE TITLE
Bones get kind of squished?

### ISSUE THREAD

**Issue by Windfave** [smartbone-org/SmartBone-2#37]
Hello, I come here for advice.
So, I am working on an Alien game, and I wanted to use smartbone 2 for applying physics to the tail of the Xenomorph.
While I somewhat succeeded, I've noticed the model's tail gets sort of squished?
![image](https://github.com/user-attachments/assets/2a35af4a-bb5e-4a99-843e-3c308faa44ab)
The tail should look like this, however, when physics are applied, the tail ends up like this:
![image](https://github.com/user-attachments/assets/1f92252d-26fb-4c60-a3cb-5ebef9bbd745)
![image](https://github.com/user-attachments/assets/baa982d5-07ff-4b7a-9fcf-6c79c05695a4)

The attributes I've used are here:
![image](https://github.com/user-attachments/assets/b8e9092d-02b9-4108-a390-46da12f793c0)
I tried to experiment with the attributes, but still couldn't find a way to have the tail not flattened.
Is there something I am doing wrong?

**Comment by JakeyWasTaken** [comment]
I believe this to be related to [this](https://devforum.roblox.com/t/smartbone-2-simulated-physics-and-collision-solution-for-bones/2728928/349)

**Comment by JakeyWasTaken** [comment]
![image](https://github.com/user-attachments/assets/1501b936-9480-44dd-afa6-baa3d16c2948)

This may solve your issue for the time being

**Comment by Windfave** [comment]
Tried it out, sadly the result is the same. First I reimported the model with those settings, didn't work, so I thought I should probably also use zeroed out animations. Did that, yet it sadly doesn't work.

**Comment by JakeyWasTaken** [comment]
Try v0.3.1

**Comment by Windfave** [comment]
Tried it out, didn't work, so I also tried 0.3.0 and even 0.2.0

Could the problem perhaps be with the model itself?

**Comment by Windfave** [comment]
Okay I feel dumb. So the issue wasn't smartbones, it was a problem with how the bones were oriented in the tail.
As you can see here, the bones were structured like this
![image](https://github.com/user-attachments/assets/f7c5e925-8244-48bf-a077-568ef54bd7dc)
And all I had to was to make the bones get auto reoriented in blender import settings to look like this:
![image](https://github.com/user-attachments/assets/89985831-7000-451e-a669-b5ba03eb9c5b)


Thank you for your efforts to help me with a fix, and I am sorry with my low iq specimen brain that led to this problem.
