### ISSUE TITLE
bones stop working

### ISSUE THREAD

**Issue by Fosforitoquemado** [smartbone-org/SmartBone-2#42]
every time my character respawn, mesh with smartbones working properly stop working when the character respawns pls help

**Comment by JakeyWasTaken** [comment]
Can you share your setup

**Comment by Fosforitoquemado** [comment]
so i tried some testing and i copied the exac same startercharacter from the demo place and paste it in my game and it happens to with that character (only added the Debug property in the hair mesh)

https://github.com/user-attachments/assets/fc88a1eb-ad6b-4c8e-9d19-3f51d830eae9

**Comment by Fosforitoquemado** [comment]
https://www.mediafire.com/file/nzyvfm1nl2p0l05/bones_dont_working.rbxl.lock/file

i made a place with the character and the smart bones script replicating the problem

**Comment by Fosforitoquemado** [comment]
i fix'd it im sorrry :/, the problem was  that i paste the client loader in the character and not the player, but thanks for replying no problem
